/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qaIXMR85nEM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"

export function OP_Navbar() {
  return (
    <header className="flex h-16 w-full items-center justify-between bg-background px-4 sm:px-6">
      <Link href="/team" className="flex items-center gap-2" prefetch={false}>
        <img src="/logo.ico" className="h-6 w-6" />
        <span className="ml-2 text-lg font-bold">KisoCore 運営チーム</span>
      </Link>
      <nav className="hidden sm:flex items-center gap-6">
        <Link href="/team" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
          トップ
        </Link>
        <Link href="/team/policy" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
          私達のポリシー
        </Link>
        <Link href="/team/team" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
          運営チーム
        </Link>
        <Link href="/team/contact" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
          お問い合わせ
        </Link>
        <Link href="/" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
          プロダクトページに戻る
        </Link>
      </nav>
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="outline" size="icon" className="sm:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left">
          <nav className="grid gap-4 py-6">
            <Link href="/team" className="text-lg font-semibold" prefetch={false}>
              トップ
            </Link>
            <Link href="/team/policy" className="text-lg font-semibold" prefetch={false}>
              私達のポリシー
            </Link>
            <Link href="/team/team" className="text-lg font-semibold" prefetch={false}>
              運営チーム
            </Link>
            <Link href="/team/contact" className="text-lg font-semibold" prefetch={false}>
              お問い合わせ
            </Link>
            <Link href="/" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              プロダクトページに戻る
             </Link>
          </nav>
        </SheetContent>
      </Sheet>
    </header>
  )
}

function MenuIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
