"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UqGlMMTnb1t
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Sheet, SheetTrigger, SheetContent, SheetClose } from "@/components/ui/sheet"
import { auth } from "@/app/firebase"
import { useRouter } from 'next/navigation'

export function Student_Navbar() {
  const router = useRouter()
  const handleSignOut = async () => {
    try{
      auth.signOut();
      router.push("/system/student/login") // awaitを削除
    }catch (e){
      console.log("Firebase Error:" + e)
    }
  };

  return (
    <header className="flex h-16 w-full items-center justify-between bg-background px-4 md:px-6">
      <div className="flex items-center gap-4">
        <Link href="/system/student" className="text-lg font-bold" prefetch={false}>
          KisoCore Student
        </Link>
      </div>
      <nav className="hidden gap-4 md:flex">
        <Link
          href="#"
          className="inline-flex h-9 items-center justify-center rounded-md bg-background px-4 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
          prefetch={false}
        >
          学習記録の確認
        </Link>
        <Link
          href="#"
          className="inline-flex h-9 items-center justify-center rounded-md bg-background px-4 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
          prefetch={false}
        >
          運営からのお知らせ
        </Link>
        <Link
          href="#"
          className="inline-flex h-9 items-center justify-center rounded-md bg-background px-4 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
          prefetch={false}
        >
          問い合わせ
        </Link>
        <Button
          variant="destructive"
          className="inline-flex h-9 items-center justify-center rounded-md px-4 text-sm font-medium transition-colors focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
          onClick={handleSignOut}
        >
          ログアウト
        </Button>
      </nav>
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="outline" size="icon" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="right" className="w-[300px]">
          <div className="flex h-16 items-center justify-between px-4">
            <Link href="/system/student" className="text-lg font-bold" prefetch={false}>
              KisoCore Student
            </Link>
            <SheetClose>
              <XIcon className="h-6 w-6" />
            </SheetClose>
          </div>
          <div className="grid gap-2 py-6 px-4">
            <Link
              href="#"
              className="flex items-center gap-2 rounded-md bg-background px-3 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2"
              prefetch={false}
            >
              学習記録の確認
            </Link>
            <Link
              href="#"
              className="flex items-center gap-2 rounded-md bg-background px-3 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2"
              prefetch={false}
            >
              運営からのお知らせ
            </Link>
            <Link
              href="#"
              className="flex items-center gap-2 rounded-md bg-background px-3 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2"
              prefetch={false}
            >
              問い合わせ
            </Link>
            <Button
          variant="destructive"
          className="inline-flex h-9 items-center justify-center rounded-md px-4 text-sm font-medium transition-colors focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
          onClick={handleSignOut}
        >
          ログアウト
        </Button>
          </div>
        </SheetContent>
      </Sheet>
    </header>
  )
}

function MenuIcon(props :any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function XIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}

