/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hMuRplw2wo4
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

export function Team_Member() {
  return (
    <div className="container grid grid-cols-1 gap-6 px-4 md:grid-cols-2 md:px-6 lg:gap-12">
      <h1 className="text-4xl">運営チーム メンバー</h1>
      <br />
      <Card className="flex flex-col items-center gap-4 rounded-lg border p-6 text-center md:text-left">
        <Avatar className="h-24 w-24">
          <AvatarImage src="/placeholder-user.jpg" />
          <AvatarFallback>れんトゥール</AvatarFallback>
        </Avatar>
        <div className="space-y-1">
          <h3 className="text-xl font-bold">れんトゥール</h3>
          <p className="text-muted-foreground">
            チームリーダー/開発者(CEO/CTO)
          </p>
        </div>
        <p className="text-muted-foreground">
          両親が使っていたパソコンから興味を持ち、ScratchからUnityと初め、現在はKisoCoreを運営・開発している。
          KisoCoreのプログラムやほぼすべての教材の作成を行っている。
          KisoCoreの開発はHNから影響されて作成している。
        </p>
      </Card>
      <Card className="flex flex-col items-center gap-4 rounded-lg border p-6 text-center md:text-left">
        <Avatar className="h-24 w-24">
          <AvatarImage src="/placeholder-user.jpg" />
          <AvatarFallback>HN</AvatarFallback>
        </Avatar>
        <div className="space-y-1">
          <h3 className="text-xl font-bold">HN</h3>
          <p className="text-muted-foreground">協力者/教材開発者</p>
        </div>
        <p className="text-muted-foreground">
          宇宙が大好き。 主に理科の教材作成を担当している。
        </p>
      </Card>
      <Card className="flex flex-col items-center gap-4 rounded-lg border p-6 text-center md:text-left">
        <Avatar className="h-24 w-24">
          <AvatarImage src="/placeholder-user.jpg" />
          <AvatarFallback>MZ</AvatarFallback>
        </Avatar>
        <div className="space-y-1">
          <h3 className="text-xl font-bold">MZ</h3>
          <p className="text-muted-foreground">協力者/教材開発者</p>
        </div>
        <p className="text-muted-foreground">
          数学が得意。 主に数学の教材作成を担当している。
        </p>
      </Card>
    </div>
  );
}
